### ISSUE TITLE
Unable to create request token using castle-sdk on .NET framework.

### ISSUE THREAD

**Issue by ssachd3va** [castle/castle-dotnet#69]
I am designing a plugin on .NET Framework and want to use castle-sdk for creating a request token, which will be used every time a user logs in. Surfed around the web and found there are inbuilt functions available for browser-sdk(web), android and iOS. But I couldn't find any equivalent function on .NET framework.

iOS code:

![image](https://user-images.githubusercontent.com/108451424/202089699-3f85631e-0893-45ad-85db-4e687dc539a7.png)

Android code:
![image](https://user-images.githubusercontent.com/108451424/202089744-8b5974b3-d5c9-44e6-8efa-77fe60d29246.png)

**Comment by wallin** [comment]
Hi @ssachd3va, the request token is created in a client-environment, such as a browser or mobile app, which is why this is not possible via the .NET SDK. Then token is then forwarded to the backend which in turns forwards this to the Castle Risk/Filter APIs. 
You can read more about this in our documentation https://docs.castle.io/docs/a-full-integration#phase-2-protecting-server-side-actions

**Comment by ssachd3va** [comment]
Hi @wallin, Thanks for your quick response. 
Since, I am developing an outlook plugin so I am just curious to know if this would be implemented in future for the .NET SDK.

**Comment by wallin** [comment]
Hi @ssachd3va, Atm. Castle only supports Web/Browser and Native Mobile app environments for generating the request token. If you wish to track activity to Castle without the request token, you may use the Log API https://reference.castle.io/#tag/logging
